<a href="https://colab.research.google.com/github/Varsha7330/EDA2/blob/main/week4_and_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**data processing tasks using python libraries**

In [3]:
import pandas as pd

# Sample data
data = {
    'Position': ['Manager', 'Assistant', 'Senior Manager', 'Intern', 'Executive'],
    'Level': [5, 2, 6, 1, 4],
    'Experience': [10, 2, 12, 0, 7],
    'Salary': [90000, 30000, 110000, 15000, 70000]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to Excel
df.to_excel('salary.xlsx', index=False)

print("File 'salary.xlsx' created successfully!")


File 'salary.xlsx' created successfully!


In [4]:
import pandas as pd
dataset= pd.read_excel('salary.xlsx')
x=dataset.iloc[:,[0]].values
y=dataset.iloc[:,[3]].values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
onehotencoder = OneHotEncoder()
ohe_x = onehotencoder.fit_transform(x)
ohe_y = onehotencoder.fit_transform(y)
x=ohe_x.toarray()
y=ohe_y.toarray()
print(x)
print(y)

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


**Pearson's Correlation**

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
x_simple=np.array([-2, -2, 0, 1, 2])
y_simple=np.array([4, 1, 3, 2, 0])
my_rho = np.corrcoef(x_simple, y_simple)
print(my_rho)

[[ 1.         -0.53033009]
 [-0.53033009  1.        ]]


**Cosine Similarity**

In [8]:
import numpy as np
from numpy.linalg import norm
a=np.array([2, 1, 2, 3, 2, 9])
b=np.array([3, 4, 2, 4, 5, 5])
cosine=np.dot(a,b)/(norm(a)*norm(b))
print("cosine similarity : ", cosine)

cosine similarity :  0.8188504723485274


**Jaccard Similarity**

In [9]:
def jaccard_similarity(list1, list2):
    s1= set(list1)
    s2= set(list2)
    return float(len(s1.intersection(s2)) / len(s1.union(s2)))
list1= ['dog', 'cat', 'cat', 'rat']
list2= ['dog', 'cat', 'mouse']
print(jaccard_similarity(list1, list2))

0.5


**Euclidean Distance**

In [15]:
import numpy as np
point1 = np.array((1, 2, 3))
point2 = np.array((1, 1, 1))
sum_sq = np.sum(np.square(point1 - point2))
print(np.sqrt(sum_sq))

2.23606797749979


**Manhattan Distance**

In [19]:
from scipy.spatial import distance
a= (1, 0, 2, 3)
b= (4, 4, 3, 1)
d=distance.cityblock(a , b)
print(d)

10
